### ISSUE TITLE
Are empty __init__.py files needed?

### ISSUE THREAD

**Issue by CsatiZoltan** [CsatiZoltan/GrainSegmentation#5]

**Comment by yxdragon** [comment]
__init__.py means it is a python package. In python2,  you can not import successfully if there is no init. In python3, it seems ok, but almost any repo also has one.

and the init file has some other suage, such as __all__, we use np.xxxx, but np is not a model, it is a package, and how can we use a package name to access the method below?

in imagepy, the init file has a specific usage, if there are many plugins in this package, we define a field: catlog = [xxx, xxx, xxx] to determin the order to show in the ui.

**Comment by yxdragon** [comment]
the find_boundaries is in imagepy. 
[here](https://github.com/Image-Py/imagepy/blob/master/imagepy/menus/Analysis/label_plg.py)

**Comment by CsatiZoltan** [comment]
Understood, then I keep the `__init__.py` files.
I know that `find_boundaries` is in ImagePy. However, I want other users to be able to use as many functionalities as possible without needing ImagePy. That is why I keep the _find_grain_boundaries_ function in the _GrainSegmentation_ class.
https://github.com/CsatiZoltan/GrainSegmentation/blob/2f26456e839fb12ef3ccbecb5584a0fd805284fa/src/grain_segmentation.py#L159

**Comment by yxdragon** [comment]
“I want other users to be able to use as many functionalities as possible without needing ImagePy”
Yes, I agree it, many imagej's plugin can only be used in ij, so they build a powerful macros. But I do not think macros and headerless is a good way. We should based a  general structure such as numpy, pandas, or shapely to write the algorithms.

And I find ImagePy is a little heavy for some usage. So I try to split the ui widgets from imagepy to a new repo. [sciwx](github.com/Image-Py/sciwx). As a pure and blank framework, which can load and add tools more flexiable. (a little like matplotlib or napari)

we can use it like this:
```python
class MyTool(Tool):
    def __init__: ...
      ...
canvas = Canvas()
canvas.add_tool(MyTool())
canvas.add_tool(MyTool2())
canvas.add_filter(xxx)
...
canvas.set_image(ndarray)
canvas.show()
```

**Comment by CsatiZoltan** [comment]
@yxdragon Let's move the general topics to the [Gitter room](https://gitter.im/Grain-Segmentation/community).
